
USE MASTER
ALTER DATABASE BPMS1 SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE BPMS1
CREATE DATABASE BPMS1


USE MASTER
ALTER DATABASE BPMS2 SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE BPMS2
CREATE DATABASE BPMS2
